version: 2

multi-ecosystem-groups:
  # Try to update Hugo go.mod and npm in one go.
  hugo:
    commit-message:
      prefix: "chore"
    schedule:
      interval: weekly
    # SemVer-breaking bumps in Docsy or Hugo modules probably need close attention.
    update-types: [minor, patch]
    exclude-patterns:
      # Hugo version is closely tied to Docsy version; avoid bumping it automatically.
      - "hugo-extended"

updates:
  - package-ecosystem: npm
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: hugo

  - package-ecosystem: gomod
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: hugo

  - package-ecosystem: github-actions
    commit-message:
      prefix: "chore(ci)"
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
